### ISSUE TITLE
Transition Stutters in some mobile devices

### ISSUE THREAD

**Issue by MananTank** [blaze-slider/blaze-slider#10]
Some users have reported that transition stutters in iOS safari and on some android devices

**Comment by robjstanley** [comment]
We're seeing this issue, but this issue has been closed. Was the bug resolved?

**Comment by MananTank** [comment]
Hi @robjstanley, Are still able to replicate the issue on the latest version?

**Comment by robjstanley** [comment]
Yeah we're using the latest 1.8.0 via CDN

This issue also seems to happen on the demos

https://user-images.githubusercontent.com/1289058/201136893-4729a02c-8ec0-49eb-9971-e913a127ed1a.MOV

**Comment by MananTank** [comment]
@robjstanley Thanks for the video

Sorry, but I don't see any stutters or dropped frames in the video you provided - seems like a standard 60fps to me. 

Can you try out the Swiper's demo on your phone - https://9ytbcw.csb.app/

Does it appear smoother? Can you also send a video of it?
