### ISSUE TITLE
Missing  {"type": "module"} to package.json

### ISSUE THREAD

**Issue by langbamit** [blaze-slider/blaze-slider#15]
You are publishing a module but not declaring it as such in package.json which makes it impossible to use (e.g. SSR)

![image](https://user-images.githubusercontent.com/43192714/197694842-41d66f01-3f56-4961-95d3-ce17db38ea95.png)

https://codesandbox.io/s/friendly-merkle-kc1f6i?file=/index.mjs

**Comment by MananTank** [comment]
Seems to be working fine without type: "module" as well
Sandbox: https://codesandbox.io/s/interesting-robinson-fmu5b6?file=/src/index.ts

May you are having this issue because you have created a Node sandbox?

**Comment by MananTank** [comment]
Let me add `type: 'module'` - seems like that should not create any problem

**Comment by MananTank** [comment]
Fixed in 2b0121589a57c4f700779031670f9febe35014a8
Fixed available on v1.7.1

@langbamit  Here's your sandbox with blaze-slider v1.7.1 : 
https://codesandbox.io/s/pensive-pasteur-bh80c0?file=/index.mjs
