### ISSUE TITLE
Programmatically jump to slide

### ISSUE THREAD

**Issue by sarabarrerariano** [blaze-slider/blaze-slider#18]
Would it be possible to provide the functionality to jump to a slide with a callback or something?

**Comment by MananTank** [comment]
Hi @sarabarrerariano,
 
There are no methods to jump to a particular slide, but there are methods to scroll the slider to go to next or previous page. I have not documented it on the website but I will shortly add them. 

You can use the `next()` and `prev()` methods available on the slider  instance

```javascript
const slider = new BlazeSlider(el, config?);

slider.prev() // go to previous page
slider.next() // go to next page

// you can also provide how many pages 
slider.prev(2) 
slider.next(2)
```
