### ISSUE TITLE
Slide callback?

### ISSUE THREAD

**Issue by nickyquinn** [blaze-slider/blaze-slider#19]
Is there anyway to detect via callback when Blaze has moved to the next slide, either via user action or when it's set to auto-play through them?

This would be really useful for lazily loading images or dynamically loading in content.

**Comment by MananTank** [comment]
Right now there are no callbacks when slider is moved, but I suggest using intersection observer for dynamic content loading and a simple loading=“lazy” attribute for natively lazy loading images

**Comment by nickyquinn** [comment]
Thanks; the observer API is the way forward in this case.
