### ISSUE TITLE
Feature request: Make small part of prev/next slide visible

### ISSUE THREAD

**Issue by ansmlc** [blaze-slider/blaze-slider#20]
Like this example from Airbnb:
![](https://i.stack.imgur.com/Bus8A.png)

**Comment by MananTank** [comment]
@ansmlc You can achieve this CSS

Checkout this sandbox: https://69o669.csb.app/ 
specially this file: https://codesandbox.io/s/blaze-slider-overflow-69o669?file=/overflow.css

**Comment by bugproof** [comment]
This doesn't work with loop: false.

This is the best slider library that actually doesn't lag except few issues
