### ISSUE TITLE
module is not defined in ES module scope

### ISSUE THREAD

**Issue by harrytran998** [blaze-slider/blaze-slider#22]
```
This file is being treated as an ES module because it has a '.js' file extension and '/Users/.../node_modules/blaze-slider/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
  ```

It seems your package is not config correctly with the commonjs. When using tools like Vitejs, in dev mode --> Default read commonjs mode, in production build just read ESM. 

You should remove the type = module in your package.json to guarantee all tools work correctly.

```
"type": "module",
"name": "blaze-slider",
 ```

**Comment by MananTank** [comment]
It's funny you mention this - I did not add `"type": "module"` earlier but there was an issue raised that without to add `"type": "module"` - https://github.com/blaze-slider/blaze-slider/issues/15 

Seems to be working fine with Vite: https://stackblitz.com/edit/vitejs-vite-aeyh3n?file=main.js

**Comment by MananTank** [comment]
@harrytran998 Can you let me know which version of blaze-slider are you using?

**Comment by harrytran998** [comment]
I use the latest blaze-slider with monorepo. Sr bcs I don't have a reproduction for you. But I think in design lib, should have two options for mask users (commonjs and module) - should not add type module in default 😆.

Besides, you should export two files `.js` for commonjs and `.mjs` for module.   Cheer!

**Comment by harrytran998** [comment]
Well, I know what exactly the problem is here. 
In your dist build folder, you expose file `.cjs.dev.js` --> I'm using Astro(Vite underhood) --> Blame about that. So after I change the name to `.cjs.js`--> It worked!

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/24296018/201245902-4a9e90a9-93a2-4dc0-93b9-7d059cdb6a6a.png">

I think you should take sometime to discover the way to export bundle files.

**Comment by MananTank** [comment]
@harrytran998 I can't replicate the issue with Astro. See the video below:

https://user-images.githubusercontent.com/22043396/201265556-9a955625-da14-4950-aafe-63064fcc64dd.mp4


Can you tell the version of the NPM & Node installed on your system?
