### ISSUE TITLE
[Feat] onChange or Slide change listener

### ISSUE THREAD

**Issue by edenizk** [blaze-slider/blaze-slider#27]
Can we have a method for listening change in slider? so that we can add some custom actions depends on slide index.

Because right now I am trying to add similar to adaptive layers logic like in slick, but unfortunately there are no listeners for me to see slide change

Another example could be:
changing a text or image in another component, or adding a custom CSS depending on the slide index.

Possible solution could be adding a callback method like change/changed to `isTransitioning` function

**Comment by MananTank** [comment]
@edenizk I'm working on it 🙌

**Comment by MananTank** [comment]
@edenizk I've added an initial implementation on 1.9.0

```javascript
 const unsubscribe = blazeSlider.onSlide((page, firstSlideIndex, lastSlideIndex) => {
     console.log(page, [firstSlideIndex, lastSlideIndex]);
 });

 // when you don't want to listen to slide changes anymore
 // unsubscribe()
```

Here's an [Example Demo](https://codesandbox.io/s/blaze-slider-playground-forked-dyhyxu?file=/index.html)

This is not yet documented, Will document it soon

**Comment by edenizk** [comment]
> @edenizk I've added an initial implementation on 1.9.0
> 
> ```javascript
>  const unsubscribe = blazeSlider.onSlide((page, firstSlideIndex, lastSlideIndex) => {
>      console.log(page, [firstSlideIndex, lastSlideIndex]);
>  });
> 
>  // when you don't want to listen to slide changes anymore
>  // unsubscribe()
> ```
> 
> Here's an [Example Demo](https://codesandbox.io/s/blaze-slider-playground-forked-dyhyxu?file=/index.html)
> 
> This is not yet documented, Will document it soon


Great, thank you 🙂

I can't wait to try it 😁
