### ISSUE TITLE
Free mode and free snap mode

### ISSUE THREAD

**Issue by katriellucas** [blaze-slider/blaze-slider#29]
Great lib btw, not sure if this has it, but if possible, could you add **free mode** and **free snap mode**? Here are some examples on keen-slider.

Free mode:
https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/basic/free-mode/javascript?file=/index.html

Free snap mode:
https://codesandbox.io/s/github/rcbyr/keen-slider-sandboxes/tree/v6/basic/free-snap-mode/javascript?file=/index.html

**Comment by MananTank** [comment]
@katriellucas 
If you want the free-mode - I suggest not using any slider library and just use the CSS scroll snapping. It is much more performant and smoother
https://css-tricks.com/practical-css-scroll-snapping/

**Comment by katriellucas** [comment]
@MananTank I was aware of scroll-snapping, but that seems to work with normal scrollable elements, I would lose the "drag" properties of the slider on desktop. I might consider my own implementation. Anyway, thanks for the tip.

**Comment by cutesquirrel** [comment]
+1
