### ISSUE TITLE
Use passive listener to improve scroll performance

### ISSUE THREAD

**Issue by jablonski** [blaze-slider/blaze-slider#32]
When running PageSpeed over a site containing Blaze Slider, it complains about missing passive listeneres to improve scroll performance, e.g.:

https://pagespeed.web.dev/report?url=https%3A%2F%2Fblaze-slider.dev%2F

Is it possible to use {passive:true} for appropriate click- & point-listeners?

**Comment by MananTank** [comment]
@jablonski Since I need to use preventDefault on touch events - I can not mark them passive. This is the same scenario for all slider libraries
