### ISSUE TITLE
Showing a slide and a half and centering when sliding through 

### ISSUE THREAD

**Issue by boyoon** [blaze-slider/blaze-slider#34]
Kind of like center mode in Slick and how it looks like in [Flickity](https://flickity.metafizzy.co/options.html)

Just wondering if this is a possibility!

**Comment by MananTank** [comment]
@boyoon Yes you can by adjusting CSS 
Example: https://codesandbox.io/s/blaze-slider-overflow-69o669?file=/overflow.css

**Comment by im-mike** [comment]
Hello

Thanks for the overflow CSS above. Is it possible to center the active slide and cut a bit or the side slides? At the moment the code only cuts off the right hand side.

This is an example of center mode (from slick):
![image](https://user-images.githubusercontent.com/53824760/211588832-07623a41-b240-4f99-b83f-22a35111f5fb.png)

**Comment by MananTank** [comment]
@im-mike Sorry, center mode is not implemented yet

**Comment by greenlevel** [comment]
I also wanted to create this. 

I added some css code to achieve this and it works when you only need 1 centered slide and see some slides on both sides.

On the class .blaze-track, i added 
margin-left: -10%;
margin-right: -10%;

and set the slides to show to 3.
