### ISSUE TITLE
Can this support thumbnails?

### ISSUE THREAD

**Issue by drewlonious** [blaze-slider/blaze-slider#37]
Common feature for ecommerce would be for thumbnails. Wondering if this is supported

**Comment by MananTank** [comment]
Can you elaborate? Do you mean images inside the slider?

**Comment by jamesli2021** [comment]
I think the OP's goal is to display exactly as Amazon's thumbnails element.

![tn](https://user-images.githubusercontent.com/95068031/213928278-4e68ba4c-57ea-440c-9bda-ce0a58510b62.jpg)

How could we override or having the ability to customize pagination?

```
<div class="blaze-pagination"></div>
```

**Comment by MananTank** [comment]
@jamesli2021 Sorry for the late reply, to create a custom pagination using the `prev()` and `next()` and `onSlide()` methods

Example: https://codesandbox.io/s/custom-pagination-bfttpg?file=/index.html

**Comment by jamesli2021** [comment]
@MananTank Thanks, I see that when clicking on the next thumbnail, the border took longer to render border. Border on previous thumbnail always appear to render quicker.

**Comment by MananTank** [comment]
@jamesli2021 This is expected because how the slider works, clicking next triggers requires more DOM manipulation to be done compared to clicking prev
