### ISSUE TITLE
Wrong class in tutorial

### ISSUE THREAD

**Issue by im-mike** [blaze-slider/blaze-slider#38]
On the setup page under pagination the class in the code example is wrong it says "pagination" instead of "blaze-pagination" - took me a little while to figure out why the pagination wasn't working for me.
https://blaze-slider.dev/docs/Tutorial/setup
![image](https://user-images.githubusercontent.com/53824760/211582865-da776f20-a93c-462f-9fe5-1fceec5cdaa0.png)

**Comment by MananTank** [comment]
@im-mike Thanks for creating the issue! Fixed in https://github.com/blaze-slider/blaze-slider/commit/0c42db9c4b83a9e2c9f8f81c07fca31a8e4d3db2
