### ISSUE TITLE
defaultConfig Rows

### ISSUE THREAD

**Issue by renchris** [blaze-slider/blaze-slider#40]
Is there a config setting for the number of rows like slick min has? If not, how would I configure blaze slider to do the same? I am migrating over from slick min

**Comment by MananTank** [comment]
There's no such config in blaze-slider but you can achieve the same result

Example: https://codesandbox.io/s/blaze-slider-playground-2-rows-i2c0d4?file=/index.html

**Comment by renchris** [comment]
If need to have the separate slider component for mobile size (regular one row) and the separate slider component for larger sizes (certain multiple rows at certain breakpoints), would that negatively affect the performance or any other rendering issues?

**Comment by MananTank** [comment]
@renchris In that case, just have two (or more) different slider components with their own separate config and styling and render the appropriate one based on the media query. This won't have any impact on perf.

**Comment by renchris** [comment]
I want the slides to the left and right of the slides to show visible (with overflow on the container visible` <div className="blaze-track-container" style={{ overflow: 'visible' }}>`), however the slide to the right isn't rendered/isn't visible until it's dragged

Is there any way to make the outer right slide visible?

**Comment by MananTank** [comment]
Hi @renchris, Sorry for the late reply. I've been super busy lately

Yes this is expected behavior if you override the `overflow: hidden` + `loop: true`

if you want to show the left slide, you have to use `loop: false` - that's what I have done on the website https://blaze-slider.dev/

**Comment by renchris** [comment]
> Hi @renchris, Sorry for the late reply. I've been super busy lately
> 
> Yes this is expected behavior if you override the `overflow: hidden` + `loop: true`
> 
> if you want to show the left slide, you have to use `loop: false` - that's what I have done on the website https://blaze-slider.dev/

Slick Slider shows the left side with the loop being true. Is there any way to have this functionality available?

**Comment by renchris** [comment]
> Hi @renchris, Sorry for the late reply. I've been super busy lately
> 
> Yes this is expected behavior if you override the `overflow: hidden` + `loop: true`
> 
> if you want to show the left slide, you have to use `loop: false` - that's what I have done on the website https://blaze-slider.dev/

Is there a way to just have one more card rendered to the left of the left-most card, and one more card rendered to the right of the right-most card?

**Comment by MananTank** [comment]
@renchris You can increase the slides `slidesToShow` to show more slides, other than that it's not possible to show more slides than `slidesToShow` without `overflow: hidden + loop: true`

**Comment by renchris** [comment]
Okay. For any case where you need to see the previous and next slides (which I presume is many), it's visually unusable with the flickering slides.

Perhaps we could have something like slick where they have an extra two cloned slides before and after to prevent this

<img width="723" alt="image" src="https://github.com/blaze-slider/blaze-slider/assets/57972348/afb1f6f4-9401-455c-98ea-cf23e18ac02a">
