### ISSUE TITLE
Detect current slide or start/end to enable/disable navigation

### ISSUE THREAD

**Issue by debatz** [blaze-slider/blaze-slider#42]
Hello,

I'm currently using keen-slider at work. 

Just seen Blaze and looks incredibly promising.

I do not see, however, a way to track current slides shown, or track start/end. If this were implemented, I'd test it to replace Keen.

I'd be willing to contribute to the library since there are not that many good options and it's a very important feature in my work. Any tips to start helping you?

Thanks!

**Comment by MananTank** [comment]
Hi @debatz, you can use the `onSlide` method to track current slides shown and other info

Example: https://codesandbox.io/s/blaze-slider-playground-ps0b9u?file=/index.html:1796-1803

**Comment by debatz** [comment]
> Hi @debatz, you can use the `onSlide` method to track current slides shown and other info
> 
> Example: https://codesandbox.io/s/blaze-slider-playground-ps0b9u?file=/index.html:1796-1803

I see, excellent! Sorry, I must've missed it in the docs.

Any tips on how to contribute to the library?

Thanks!
