### ISSUE TITLE
Prevent click events from slider item if the user is only dragging 

### ISSUE THREAD

**Issue by sholzer** [blaze-slider/blaze-slider#49]
I have a slider with clickable items, when i try to drag the slider the click event is triggered immediately, can you please fix it ?

**Comment by MananTank** [comment]
@sholzer Are you using the latest version?

**Comment by sholzer** [comment]
yes i'm using v1.9.1

**Comment by sholzer** [comment]
Just noticed that it only occurs on the first and last item:

https://codesandbox.io/p/sandbox/blaze-slider-link-test-ngstwb?file=%2Fsrc%2FApp.vue
