### ISSUE TITLE
[FEAT] Vertical Slides.

### ISSUE THREAD

**Issue by tomikaka22** [blaze-slider/blaze-slider#50]
This seems to be a very lean replacement for other JavaScript swiper modules. However, there's a feature missing.

**Can you please add a vertical slider, so you can swipe on the Y axis instead on the X axis?**

**Comment by MananTank** [comment]
@tomikaka22 To keep the slider lean, There's no plan for adding vertical support at the moment. I suggest using css scroll snapping instead: https://css-tricks.com/practical-css-scroll-snapping/
