### ISSUE TITLE
Horizontal Overflow when with images and content

### ISSUE THREAD

**Issue by praveenc78** [blaze-slider/blaze-slider#55]
Loving the slider so far. I have added some images along with content for each slide and the issue I am facing is when the device width goes below 600px I am seeing horizontal scrollbar and slide image and content overflow. I have created a CodePen to show what I have so far.

[CodePen Link](https://codepen.io/praveenc78/pen/eYPzLXd)

Any tip how to avoid this.
Thanks and Appreciate it

**Comment by MananTank** [comment]
@praveenc78 Removing the `display:flex` on `.pc-fl` fixes the issue

<img width="823" alt="image" src="https://user-images.githubusercontent.com/22043396/232705142-3bc99da1-220d-45b7-a55a-5384e1784341.png">

**Comment by praveenc78** [comment]
Thank you so much
