### ISSUE TITLE
Limit Pagination buttons

### ISSUE THREAD

**Issue by greenlevel** [blaze-slider/blaze-slider#60]
Hi All, 
I was checking out the settings. 
But is it possible to limit the pagination buttons.

Even if there is a large number of slides, that is still shows for example 5 buttons max. 

Thanks in advance!

**Comment by MananTank** [comment]
That's not currently possible out of the box - but you can create custom pagination buttons by using the [methods](https://blaze-slider.dev/docs/api/methods) available on slider
