### ISSUE TITLE
Swiping quickly on mobile cause stuttering

### ISSUE THREAD

**Issue by viktorrudi** [blaze-slider/blaze-slider#8]
Device: iPhone 12 Mini
Browser: Tested on Safari and Chrome

**Comment by MananTank** [comment]
@viktorrudi If possible, Can you attach a Video?

**Comment by viktorrudi** [comment]
Strange, I'm unable to reproduce it today.

**Comment by MananTank** [comment]
@viktorrudi Maybe it got resolved when I added optimizations for CSS variables in 1.6.0
